<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>PaperDotNet.OptimizationBenchmark</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/Extensions/PaperDotNet.StorageOptimization/PaperDotNet.StorageOptimization.csproj" />
    <ProjectReference Include="../../../src/Modules/Documents/PaperDotNet.Documents/PaperDotNet.Documents.csproj" />
  </ItemGroup>
</Project>
