<Project Sdk="Microsoft.NET.Sdk">
  <!-- Long-running operations and recurring jobs. -->
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\PaperDotNet.Jobs.Contracts\PaperDotNet.Jobs.Contracts.csproj" />
    <ProjectReference Include="..\..\Tenancy\PaperDotNet.Tenancy.Contracts\PaperDotNet.Tenancy.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\PaperDotNet.Api\PaperDotNet.Api.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\PaperDotNet.Persistence\PaperDotNet.Persistence.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\PaperDotNet.Messaging\PaperDotNet.Messaging.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Cronos" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="PaperDotNet.UnitTests" />
    <InternalsVisibleTo Include="PaperDotNet.IntegrationTests" />
  </ItemGroup>
</Project>
