using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace PaperDotNet.Extensions.Generator;

/// <summary>
/// Finds assemblies referenced by the host that carry
/// <c>[assembly: PaperDotNetExtension(typeof(X))]</c> and generates
/// <c>PaperDotNet.Extensions.Generated.ReferencedExtensions.Create()</c>, which
/// instantiates them. Build-time discovery: no runtime scanning (ADR-0014).
/// </summary>
[Generator]
public sealed class ExtensionRegistrationGenerator : IIncrementalGenerator
{
    private const string AttributeName = "PaperDotNet.Extensions.PaperDotNetExtensionAttribute";
    private const string ExtensionInterface = "PaperDotNet.Extensions.IExtension";

    private static readonly DiagnosticDescriptor InvalidExtension = new(
        "PDN0001",
        "Invalid extension type",
        "Extension type '{0}' in assembly '{1}' must be a public, non-abstract class implementing IExtension with a public parameterless constructor",
        "PaperDotNet.Extensions",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var discovered = context.CompilationProvider.Select(static (compilation, _) => Discover(compilation));
        context.RegisterSourceOutput(discovered, static (output, result) =>
        {
            foreach (var invalid in result.Invalid)
            {
                output.ReportDiagnostic(Diagnostic.Create(InvalidExtension, Location.None, invalid.Type, invalid.Assembly));
            }

            if (result.SdkReferenced)
            {
                output.AddSource("ReferencedExtensions.g.cs", SourceText.From(Render(result.Types), Encoding.UTF8));
            }
        });
    }

    private static Result Discover(Compilation compilation)
    {
        var extensionInterface = compilation.GetTypeByMetadataName(ExtensionInterface);
        if (extensionInterface is null)
        {
            return new Result(false, ImmutableArray<string>.Empty, ImmutableArray<(string, string)>.Empty);
        }

        var types = new List<string>();
        var invalid = new List<(string, string)>();
        var assemblies = compilation.SourceModule.ReferencedAssemblySymbols.Append(compilation.Assembly);
        foreach (var assembly in assemblies)
        {
            foreach (var attribute in assembly.GetAttributes())
            {
                if (attribute.AttributeClass?.ToDisplayString() != AttributeName
                    || attribute.ConstructorArguments.Length != 1
                    || attribute.ConstructorArguments[0].Value is not INamedTypeSymbol type)
                {
                    continue;
                }

                var name = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var valid = type.DeclaredAccessibility == Accessibility.Public
                            && type.TypeKind == TypeKind.Class
                            && !type.IsAbstract
                            && type.AllInterfaces.Contains(extensionInterface, SymbolEqualityComparer.Default)
                            && type.InstanceConstructors.Any(c => c.Parameters.Length == 0 && c.DeclaredAccessibility == Accessibility.Public);
                if (valid)
                {
                    types.Add(name);
                }
                else
                {
                    invalid.Add((name, assembly.Name));
                }
            }
        }

        return new Result(true, types.Distinct().OrderBy(t => t, System.StringComparer.Ordinal).ToImmutableArray(), invalid.ToImmutableArray());
    }

    private static string Render(ImmutableArray<string> types)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/> by PaperDotNet.Extensions.Generator");
        builder.AppendLine("namespace PaperDotNet.Extensions.Generated;");
        builder.AppendLine();
        builder.AppendLine("/// <summary>Extensions referenced by this build (found at compile time).</summary>");
        builder.AppendLine("internal static class ReferencedExtensions");
        builder.AppendLine("{");
        builder.AppendLine("    public static global::System.Collections.Generic.IReadOnlyList<global::PaperDotNet.Extensions.IExtension> Create() =>");
        builder.AppendLine("    [");
        foreach (var type in types)
        {
            builder.Append("        new ").Append(type).AppendLine("(),");
        }

        builder.AppendLine("    ];");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private sealed class Result(bool sdkReferenced, ImmutableArray<string> types, ImmutableArray<(string Type, string Assembly)> invalid)
        : System.IEquatable<Result>
    {
        public bool SdkReferenced { get; } = sdkReferenced;

        public ImmutableArray<string> Types { get; } = types;

        public ImmutableArray<(string Type, string Assembly)> Invalid { get; } = invalid;

        public bool Equals(Result? other) =>
            other is not null && SdkReferenced == other.SdkReferenced && Types.SequenceEqual(other.Types) && Invalid.SequenceEqual(other.Invalid);

        public override bool Equals(object? obj) => Equals(obj as Result);

        public override int GetHashCode() => Types.Length ^ Invalid.Length;
    }
}
