<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
  <PropertyGroup>
    <!-- Test names use underscores; tests need no XML docs. -->
    <NoWarn>$(NoWarn);CA1707;CA1515;CA2007;CA1861</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
