<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\BuildingBlocks\PaperDotNet.Api\PaperDotNet.Api.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\PaperDotNet.Persistence.PostgreSql\PaperDotNet.Persistence.PostgreSql.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\PaperDotNet.Persistence.Sqlite\PaperDotNet.Persistence.Sqlite.csproj" />
    <ProjectReference Include="..\..\src\Modules\Tenancy\PaperDotNet.Tenancy\PaperDotNet.Tenancy.csproj" />
    <ProjectReference Include="..\..\src\Modules\Identity\PaperDotNet.Identity\PaperDotNet.Identity.csproj" />
    <ProjectReference Include="..\..\src\Modules\Workspaces\PaperDotNet.Workspaces\PaperDotNet.Workspaces.csproj" />
    <ProjectReference Include="..\..\src\Modules\Lists\PaperDotNet.Lists\PaperDotNet.Lists.csproj" />
    <ProjectReference Include="..\..\src\Modules\Jobs\PaperDotNet.Jobs\PaperDotNet.Jobs.csproj" />
    <ProjectReference Include="..\..\src\Modules\Taxonomy\PaperDotNet.Taxonomy\PaperDotNet.Taxonomy.csproj" />
  </ItemGroup>
</Project>
