<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../PaperDotNet.Extensions.Abstractions/PaperDotNet.Extensions.Abstractions.csproj" />
    <ProjectReference Include="../PaperDotNet.Extensions.Analyzers/PaperDotNet.Extensions.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" />
    <EmbeddedResource Include="extension.json" LogicalName="paperdotnet.extension.json" />
    <InternalsVisibleTo Include="PaperDotNet.OptimizationBenchmark" />
    <InternalsVisibleTo Include="PaperDotNet.UnitTests" />
    <InternalsVisibleTo Include="PaperDotNet.IntegrationTests" />
  </ItemGroup>
</Project>
