<Project Sdk="Microsoft.NET.Sdk">
  <!-- Workspaces (spaces for a team or project) with owners, members and visitors. -->
  <Import Project="..\..\AotModule.props" />
  <ItemGroup>
    <ProjectReference Include="..\PaperDotNet.Workspaces.Contracts\PaperDotNet.Workspaces.Contracts.csproj" />
    <ProjectReference Include="..\..\Identity\PaperDotNet.Identity.Contracts\PaperDotNet.Identity.Contracts.csproj" />
    <ProjectReference Include="..\..\Provisioning\PaperDotNet.Provisioning.Contracts\PaperDotNet.Provisioning.Contracts.csproj" />
  </ItemGroup>
</Project>
