/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppWIndexRouteImport } from './routes/_app/w/index'
import { Route as AppWWorkspaceIdIndexRouteImport } from './routes/_app/w/$workspaceId/index'
import { Route as AppWWorkspaceIdLListIdIndexRouteImport } from './routes/_app/w/$workspaceId/l/$listId/index'
import { Route as AppWWorkspaceIdLListIdRecycleBinRouteImport } from './routes/_app/w/$workspaceId/l/$listId/recycle-bin'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppWIndexRoute = AppWIndexRouteImport.update({
  id: '/w/',
  path: '/w/',
  getParentRoute: () => AppRoute,
} as any)
const AppWWorkspaceIdIndexRoute = AppWWorkspaceIdIndexRouteImport.update({
  id: '/w/$workspaceId/',
  path: '/w/$workspaceId/',
  getParentRoute: () => AppRoute,
} as any)
const AppWWorkspaceIdLListIdIndexRoute =
  AppWWorkspaceIdLListIdIndexRouteImport.update({
    id: '/w/$workspaceId/l/$listId/',
    path: '/w/$workspaceId/l/$listId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppWWorkspaceIdLListIdRecycleBinRoute =
  AppWWorkspaceIdLListIdRecycleBinRouteImport.update({
    id: '/w/$workspaceId/l/$listId/recycle-bin',
    path: '/w/$workspaceId/l/$listId/recycle-bin',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/notifications': typeof AppNotificationsRoute
  '/w/': typeof AppWIndexRoute
  '/w/$workspaceId/': typeof AppWWorkspaceIdIndexRoute
  '/w/$workspaceId/l/$listId/recycle-bin': typeof AppWWorkspaceIdLListIdRecycleBinRoute
  '/w/$workspaceId/l/$listId/': typeof AppWWorkspaceIdLListIdIndexRoute
}
export interface FileRoutesByTo {
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/notifications': typeof AppNotificationsRoute
  '/': typeof AppIndexRoute
  '/w': typeof AppWIndexRoute
  '/w/$workspaceId': typeof AppWWorkspaceIdIndexRoute
  '/w/$workspaceId/l/$listId/recycle-bin': typeof AppWWorkspaceIdLListIdRecycleBinRoute
  '/w/$workspaceId/l/$listId': typeof AppWWorkspaceIdLListIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/w/': typeof AppWIndexRoute
  '/_app/w/$workspaceId/': typeof AppWWorkspaceIdIndexRoute
  '/_app/w/$workspaceId/l/$listId/recycle-bin': typeof AppWWorkspaceIdLListIdRecycleBinRoute
  '/_app/w/$workspaceId/l/$listId/': typeof AppWWorkspaceIdLListIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/login'
    | '/notifications'
    | '/w/'
    | '/w/$workspaceId/'
    | '/w/$workspaceId/l/$listId/recycle-bin'
    | '/w/$workspaceId/l/$listId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/callback'
    | '/login'
    | '/notifications'
    | '/'
    | '/w'
    | '/w/$workspaceId'
    | '/w/$workspaceId/l/$listId/recycle-bin'
    | '/w/$workspaceId/l/$listId'
  id:
    | '__root__'
    | '/_app'
    | '/callback'
    | '/login'
    | '/_app/notifications'
    | '/_app/'
    | '/_app/w/'
    | '/_app/w/$workspaceId/'
    | '/_app/w/$workspaceId/l/$listId/recycle-bin'
    | '/_app/w/$workspaceId/l/$listId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/w/': {
      id: '/_app/w/'
      path: '/w'
      fullPath: '/w/'
      preLoaderRoute: typeof AppWIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/w/$workspaceId/': {
      id: '/_app/w/$workspaceId/'
      path: '/w/$workspaceId'
      fullPath: '/w/$workspaceId/'
      preLoaderRoute: typeof AppWWorkspaceIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/w/$workspaceId/l/$listId/': {
      id: '/_app/w/$workspaceId/l/$listId/'
      path: '/w/$workspaceId/l/$listId'
      fullPath: '/w/$workspaceId/l/$listId/'
      preLoaderRoute: typeof AppWWorkspaceIdLListIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/w/$workspaceId/l/$listId/recycle-bin': {
      id: '/_app/w/$workspaceId/l/$listId/recycle-bin'
      path: '/w/$workspaceId/l/$listId/recycle-bin'
      fullPath: '/w/$workspaceId/l/$listId/recycle-bin'
      preLoaderRoute: typeof AppWWorkspaceIdLListIdRecycleBinRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppWIndexRoute: typeof AppWIndexRoute
  AppWWorkspaceIdIndexRoute: typeof AppWWorkspaceIdIndexRoute
  AppWWorkspaceIdLListIdRecycleBinRoute: typeof AppWWorkspaceIdLListIdRecycleBinRoute
  AppWWorkspaceIdLListIdIndexRoute: typeof AppWWorkspaceIdLListIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppNotificationsRoute: AppNotificationsRoute,
  AppIndexRoute: AppIndexRoute,
  AppWIndexRoute: AppWIndexRoute,
  AppWWorkspaceIdIndexRoute: AppWWorkspaceIdIndexRoute,
  AppWWorkspaceIdLListIdRecycleBinRoute: AppWWorkspaceIdLListIdRecycleBinRoute,
  AppWWorkspaceIdLListIdIndexRoute: AppWWorkspaceIdLListIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  CallbackRoute: CallbackRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
