/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppApprovalsRouteImport } from './routes/_app/approvals'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppFFolderIdRouteImport } from './routes/_app/f/$folderId'
import { Route as AppWIndexRouteImport } from './routes/_app/w/index'
import { Route as AppWWorkspaceIdIndexRouteImport } from './routes/_app/w/$workspaceId/index'
import { Route as AppWWorkspaceIdLListIdIndexRouteImport } from './routes/_app/w/$workspaceId/l/$listId/index'
import { Route as AppWWorkspaceIdLListIdRecycleBinRouteImport } from './routes/_app/w/$workspaceId/l/$listId/recycle-bin'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppFFolderIdRoute = AppFFolderIdRouteImport.update({
  id: '/f/$folderId',
  path: '/f/$folderId',
  getParentRoute: () => AppRoute,
} as any)
const AppWIndexRoute = AppWIndexRouteImport.update({
  id: '/w/',
  path: '/w/',
  getParentRoute: () => AppRoute,
} as any)
const AppWWorkspaceIdIndexRoute = AppWWorkspaceIdIndexRouteImport.update({
  id: '/w/$workspaceId/',
  path: '/w/$workspaceId/',
  getParentRoute: () => AppRoute,
} as any)
const AppWWorkspaceIdLListIdIndexRoute =
  AppWWorkspaceIdLListIdIndexRouteImport.update({
    id: '/w/$workspaceId/l/$listId/',
    path: '/w/$workspaceId/l/$listId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppWWorkspaceIdLListIdRecycleBinRoute =
  AppWWorkspaceIdLListIdRecycleBinRouteImport.update({
    id: '/w/$workspaceId/l/$listId/recycle-bin',
    path: '/w/$workspaceId/l/$listId/recycle-bin',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/approvals': typeof AppApprovalsRoute
  '/calendar': typeof AppCalendarRoute
  '/inbox': typeof AppInboxRoute
  '/notifications': typeof AppNotificationsRoute
  '/search': typeof AppSearchRoute
  '/tasks': typeof AppTasksRoute
  '/f/$folderId': typeof AppFFolderIdRoute
  '/w/': typeof AppWIndexRoute
  '/w/$workspaceId/': typeof AppWWorkspaceIdIndexRoute
  '/w/$workspaceId/l/$listId/recycle-bin': typeof AppWWorkspaceIdLListIdRecycleBinRoute
  '/w/$workspaceId/l/$listId/': typeof AppWWorkspaceIdLListIdIndexRoute
}
export interface FileRoutesByTo {
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/approvals': typeof AppApprovalsRoute
  '/calendar': typeof AppCalendarRoute
  '/inbox': typeof AppInboxRoute
  '/notifications': typeof AppNotificationsRoute
  '/search': typeof AppSearchRoute
  '/tasks': typeof AppTasksRoute
  '/': typeof AppIndexRoute
  '/f/$folderId': typeof AppFFolderIdRoute
  '/w': typeof AppWIndexRoute
  '/w/$workspaceId': typeof AppWWorkspaceIdIndexRoute
  '/w/$workspaceId/l/$listId/recycle-bin': typeof AppWWorkspaceIdLListIdRecycleBinRoute
  '/w/$workspaceId/l/$listId': typeof AppWWorkspaceIdLListIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/': typeof AppIndexRoute
  '/_app/f/$folderId': typeof AppFFolderIdRoute
  '/_app/w/': typeof AppWIndexRoute
  '/_app/w/$workspaceId/': typeof AppWWorkspaceIdIndexRoute
  '/_app/w/$workspaceId/l/$listId/recycle-bin': typeof AppWWorkspaceIdLListIdRecycleBinRoute
  '/_app/w/$workspaceId/l/$listId/': typeof AppWWorkspaceIdLListIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/login'
    | '/approvals'
    | '/calendar'
    | '/inbox'
    | '/notifications'
    | '/search'
    | '/tasks'
    | '/f/$folderId'
    | '/w/'
    | '/w/$workspaceId/'
    | '/w/$workspaceId/l/$listId/recycle-bin'
    | '/w/$workspaceId/l/$listId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/callback'
    | '/login'
    | '/approvals'
    | '/calendar'
    | '/inbox'
    | '/notifications'
    | '/search'
    | '/tasks'
    | '/'
    | '/f/$folderId'
    | '/w'
    | '/w/$workspaceId'
    | '/w/$workspaceId/l/$listId/recycle-bin'
    | '/w/$workspaceId/l/$listId'
  id:
    | '__root__'
    | '/_app'
    | '/callback'
    | '/login'
    | '/_app/approvals'
    | '/_app/calendar'
    | '/_app/inbox'
    | '/_app/notifications'
    | '/_app/search'
    | '/_app/tasks'
    | '/_app/'
    | '/_app/f/$folderId'
    | '/_app/w/'
    | '/_app/w/$workspaceId/'
    | '/_app/w/$workspaceId/l/$listId/recycle-bin'
    | '/_app/w/$workspaceId/l/$listId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/f/$folderId': {
      id: '/_app/f/$folderId'
      path: '/f/$folderId'
      fullPath: '/f/$folderId'
      preLoaderRoute: typeof AppFFolderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/w/': {
      id: '/_app/w/'
      path: '/w'
      fullPath: '/w/'
      preLoaderRoute: typeof AppWIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/w/$workspaceId/': {
      id: '/_app/w/$workspaceId/'
      path: '/w/$workspaceId'
      fullPath: '/w/$workspaceId/'
      preLoaderRoute: typeof AppWWorkspaceIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/w/$workspaceId/l/$listId/': {
      id: '/_app/w/$workspaceId/l/$listId/'
      path: '/w/$workspaceId/l/$listId'
      fullPath: '/w/$workspaceId/l/$listId/'
      preLoaderRoute: typeof AppWWorkspaceIdLListIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/w/$workspaceId/l/$listId/recycle-bin': {
      id: '/_app/w/$workspaceId/l/$listId/recycle-bin'
      path: '/w/$workspaceId/l/$listId/recycle-bin'
      fullPath: '/w/$workspaceId/l/$listId/recycle-bin'
      preLoaderRoute: typeof AppWWorkspaceIdLListIdRecycleBinRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppInboxRoute: typeof AppInboxRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSearchRoute: typeof AppSearchRoute
  AppTasksRoute: typeof AppTasksRoute
  AppIndexRoute: typeof AppIndexRoute
  AppFFolderIdRoute: typeof AppFFolderIdRoute
  AppWIndexRoute: typeof AppWIndexRoute
  AppWWorkspaceIdIndexRoute: typeof AppWWorkspaceIdIndexRoute
  AppWWorkspaceIdLListIdRecycleBinRoute: typeof AppWWorkspaceIdLListIdRecycleBinRoute
  AppWWorkspaceIdLListIdIndexRoute: typeof AppWWorkspaceIdLListIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApprovalsRoute: AppApprovalsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppInboxRoute: AppInboxRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSearchRoute: AppSearchRoute,
  AppTasksRoute: AppTasksRoute,
  AppIndexRoute: AppIndexRoute,
  AppFFolderIdRoute: AppFFolderIdRoute,
  AppWIndexRoute: AppWIndexRoute,
  AppWWorkspaceIdIndexRoute: AppWWorkspaceIdIndexRoute,
  AppWWorkspaceIdLListIdRecycleBinRoute: AppWWorkspaceIdLListIdRecycleBinRoute,
  AppWWorkspaceIdLListIdIndexRoute: AppWWorkspaceIdLListIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  CallbackRoute: CallbackRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
