<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="System.Formats.Cbor" />
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\PaperDotNet.Host\PaperDotNet.Host.csproj" />
    <ProjectReference Include="..\..\samples\PaperDotNet.Samples.Invoices\PaperDotNet.Samples.Invoices.csproj" />
    <ProjectReference Include="..\..\samples\PaperDotNet.Samples.Invoices.Migrations.Sqlite\PaperDotNet.Samples.Invoices.Migrations.Sqlite.csproj" />
    <ProjectReference Include="..\..\samples\PaperDotNet.Samples.Invoices.Migrations.PostgreSql\PaperDotNet.Samples.Invoices.Migrations.PostgreSql.csproj" />
  </ItemGroup>
</Project>
